version: '3.3'
services:
  kong-db:
    image: 'postgres:9.6'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-volume:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: 'echo "select 1" | psql -U kong kong || exit 1'
      interval: 1m
      timeout: 3s
      retries: 3
#    restart: unless-stopped

  kong-migration:
    image: 'kong:0.14'
#    depends_on:
#      kong-database:
#        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations up  # use `kong migrations bootstrap` with kong:0.15

  kong:
    image: 'kong:0.14'
    ports:
      - 8000:8000  # proxy
      - 8443:8443  # proxy ssl
      - 8001:8001  # admin api
      - 8444:8444  # admin api ssl
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    links:
      - kong-db
    depends_on:
      - kong-db
    healthcheck:
      test: 'curl -f http://localhost:8001/status || exit 1'
      interval: 1m
      timeout: 3s
      retries: 3
#    restart: unless-stopped

  kong-ui:
    image: 'pgbi/kong-dashboard:v3.5.0'
    ports:
      - 8080:8080
    command: "start --kong-url http://kong:8001"

